# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Sub-MicroSig
version:      0.03
version_from: lib/Sub/MicroSig.pm
installdirs:  site
requires:
    Hook::LexWrap:                 0
    Params::Validate::Micro:       0.02
    Sub::Identify:                 0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
